### ISSUE TITLE
axios invalid url

### ISSUE THREAD

**Issue by lindesvard** [Studio123ca/strapi-plugin-image-color-palette#2]
Hey, 

Thanks for neat plugin! I'm quite new to strapi so maybe I have missed something obvious here.

After installed the plugin and I uploaded a new image I got an error in the terminal about invalid url. So I looked at the code and noticed the `url` ([here](https://github.com/Studio123ca/strapi-plugin-image-color-palette/blob/main/server/services/image-color-palette.js#L29)) does not have any host information, only pathname `/uploads/my-file.png` instead of `http://localhost:1337/uploads/my-file.png`. 

Hard coded the domain for now and everything works great 😂

**Comment by codymx** [comment]
@lindesvard This should be fixed in the newest release 😄

**Comment by lindesvard** [comment]
Thanks 🔥
